# Generated by Django 4.1.1 on 2022-09-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_alter_player_accepted_date_alter_player_fights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fights',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='forts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='gangs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='zvz',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
