# Generated by Django 4.1.1 on 2022-09-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_player_fights_alter_player_forts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='summ',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
