# Generated by Django 4.1.1 on 2022-09-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_player_summ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='summ',
        ),
    ]
